Feature/406153 confirm company details
DEFRA/epr-frontend-accountmanagement-microservice pull request #23
Opened 2024-07-12 10:14 UTC by Ehsan-Hatami

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/Address.cs
> +    public Address()
Don't need an empty constructor

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/Address.cs
> +        SubBuildingName = office.SubBuildingName;
Could use AutoMapper here. Will make the code cleaner

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/Address.cs
> +    public Address(RegisteredOfficeAddress? office) : this()
the default constructor does not need referencing

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/CompanyHouse/Company.cs
> +        public Company()
Don't need an empty constructor

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/CompanyHouse/Company.cs
> +        public Company(CompaniesHouseCompany? organisation) : this()
Don't need to call the default constructor since it doesn't do anything

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/CompanyHouse/Company.cs
> +            CompaniesHouseNumber = organisation.Organisation.RegistrationNumber ?? string.Empty;
Could use AutoMapper here

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/ConnectionPerson.cs
> +}
Did this class even need changing!?

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        SetBackLink(session, PagePath.ManageAccount);
Have you checked the back link works? I had to put extra functionality in to get it to work correctly.

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +            return RedirectToAction(PagePath.Error, nameof(ErrorController.Error), new
Surely this is a BadRequest (400) rather than an outright error? So surely return BadRequest() is better suited?

2024-07-12 14:59 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        var viewModel = new ConfirmCompanyDetailsViewModel
Use AutoMapper

2024-07-12 15:29 UTC, tim-powell-eviden requested changes
Classes need to either be covered by unit tests or tagged as intentionally excluded, in order to keep our coverage percentage up.

2024-07-12 15:29 UTC, tim-powell-eviden commented on src/FrontendAccountManagement.Core/Models/Address.cs
Should we really be excluding this class from unit tests?
I know it's a very simple class, but I've definately come across issues in the past where bugs have occured in even simple classes due to typos when assigning values in the constructor - writing tests for even basic fuctionalty is good practice imo.

2024-07-12 15:29 UTC, tim-powell-eviden commented on src/FrontendAccountManagement.Core/Models/Address.cs
These data classes - possibly they should be records rather than classes?

2024-07-15 11:26 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Models/Address.cs
> +        SubBuildingName = office.SubBuildingName;
done

2024-07-15 11:26 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Models/CompanyHouse/Company.cs
> +        public Company()
removed

2024-07-15 11:26 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Models/CompanyHouse/Company.cs
> +        public Company(CompaniesHouseCompany? organisation) : this()
no, removed

2024-07-15 11:26 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Models/Address.cs
> +    public Address(RegisteredOfficeAddress? office) : this()
removed

2024-07-15 11:26 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Models/CompanyHouse/Company.cs
> +            CompaniesHouseNumber = organisation.Organisation.RegistrationNumber ?? string.Empty;
done

2024-07-15 11:26 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        SetBackLink(session, PagePath.ManageAccount);
fixed it

2024-07-15 11:28 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +            return RedirectToAction(PagePath.Error, nameof(ErrorController.Error), new
this happens when we cant find company ( the response is null) so I made it actually 404 not found. but Im open to suggestions. if you think its 400 I dont have strong opposite opinion and i can change it to 400.

2024-07-15 11:28 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        var viewModel = new ConfirmCompanyDetailsViewModel
done

2024-07-15 11:46 UTC, shehzad-ismail8 approved these changes

2024-07-15 11:53 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Models/CompaniesHouse/AddressDto.cs
> +    public class CountryDto
We should have one file for one class.

2024-07-15 11:53 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +        var response = await _httpClient.GetAsync($"/api/companies-house?id={companyHouseNumber}");
I think end points have been put into the configuration file - can we check and address if neceesary?

2024-07-15 11:53 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Services/MockedFacadeService.cs
> +        var stubResponse = new CompaniesHouseResponse
Why do we have hard coded data?

2024-07-15 11:53 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        var companiesHouseData = await _facadeService.GetCompaniesHouseResponseAsync(organisationData.OrganisationNumber);
what happens if organisationdata is null? (It's possible it can't be null, but if so, we should really be using First(), not FirstOrDefault()

2024-07-15 11:53 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Web/ViewModels/AccountManagement/AddressViewModel.cs
> +        private string Separator => !string.IsNullOrEmpty(BuildingNumber) ? " " : "";
Use IsNullOrWhitespace instead - it's a more recent function available.

2024-07-15 12:10 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +        var response = await _httpClient.GetAsync($"/api/companies-house?id={companyHouseNumber}");
I cant actually see if they have moved over to configs

2024-07-15 12:12 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Core/Models/CompaniesHouse/AddressDto.cs
> +    public class CountryDto
done

2024-07-15 12:12 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        var companiesHouseData = await _facadeService.GetCompaniesHouseResponseAsync(organisationData.OrganisationNumber);
done

2024-07-15 12:12 UTC, Ehsan-Hatami commented on src/FrontendAccountManagement.Web/ViewModels/AccountManagement/AddressViewModel.cs
> +        private string Separator => !string.IsNullOrEmpty(BuildingNumber) ? " " : "";
done

2024-07-15 12:14 UTC, NikPeters-Atos commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +        var response = await _httpClient.GetAsync($"/api/companies-house?id={companyHouseNumber}");
Checkout GetUserAccounts on the FacadeService - it uses a config value for the url

2024-07-15 12:28 UTC, merged