Sonar qube fixes/401508 frontend accountmanagement microservice
DEFRA/epr-frontend-accountmanagement-microservice pull request #40
Opened 2024-07-23 08:51 UTC by MVarkusEviden

2024-07-26 15:03 UTC, scdefra approved these changes

2024-07-31 14:59 UTC, scdefra requested changes

2024-07-31 14:59 UTC, scdefra commented on src/FrontendAccountManagement.Web/Controllers/PermissionManagement/PermissionManagementController.cs
> +            (string nextPagePath, string actionName, PersonRole? personRole) = GetCahngeAccountPermissionDataToDecideNextAction(
spelling mistake on the method name

2024-08-01 11:14 UTC, scdefra submitted a review, later dismissed

2024-08-02 08:42 UTC, hardik-desai-kcl commented
@MVarkusEviden I can see that you haven't run the build pipeline againts new SonarQube instance, you need to queue in a build manually and select SonarQubeLatest
<img width="431" alt="image" src="https://github.com/user-attachments/assets/ea90fcca-b2e0-4aad-8bda-538610e11aaa">

2024-08-02 09:06 UTC, hardik-desai-kcl commented
Could you please also fix these build warnings

Resources\Views\AccountManagement\TeamMemberEmail.cy.resx : warning MSB3568: Duplicate resource name "EmailTooLongErrorMessage" is not allowed, ignored.

FrontendAccountManagement.Web.UnitTests\Sessions\SessionManagerTests.cs(20,20,20,33): warning S4487: Remove this unread private field '_sessionBytes' or refactor the code to use its value. (https://rules.sonarsource.com/csharp/RSPEC-4487)

FrontendAccountManagement.Web.UnitTests\Controllers\Home\HomeControllerTests.cs(15,43,15,54): warning S4487: Remove this unread private field '_loggerMock' or refactor the code to use its value. (https://rules.sonarsource.com/csharp/RSPEC-4487)

FrontendAccountManagement.Web.UnitTests\ViewComponents\PrimaryNavigationTests.cs(19,29,19,45): warning S4487: Remove this unread private field '_landingPageLink' or refactor the code to use its value. (https://rules.sonarsource.com/csharp/RSPEC-4487)

2024-08-14 09:26 UTC, hardik-desai-kcl approved these changes

2024-08-14 09:41 UTC, scdefra approved these changes

2024-08-22 07:37 UTC, davidtonthat commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +            connectionWithEnrolments.Enrolments.Count <= 0 ||
This should be .Count == 0 since this is a logical operation, not a numeric one.

2024-08-22 07:47 UTC, davidtonthat commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +        return connectionWithEnrolments?.Enrolments.FirstOrDefault(e => e.ServiceRoleKey.Equals(serviceRoleKey))?.EnrolmentStatus;
The call FirstOrDefault() should be replaced by Find() for consistency.

2024-08-22 07:58 UTC, davidtonthat requested changes
Some small suggestions.

2024-08-22 08:55 UTC, RaveendraAttota commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +            connectionWithEnrolments.Enrolments.Count <= 0 ||
Fixed it

2024-08-22 08:56 UTC, RaveendraAttota commented on src/FrontendAccountManagement.Core/Services/FacadeService.cs
> +        return connectionWithEnrolments?.Enrolments.FirstOrDefault(e => e.ServiceRoleKey.Equals(serviceRoleKey))?.EnrolmentStatus;
Find method isn't available and sonarqube isn't showing any issues here

2024-08-22 09:50 UTC, davidtonthat approved these changes

2024-08-22 12:30 UTC, hardik-desai-kcl approved these changes

2024-08-27 10:10 UTC, EvidenPete approved these changes

2024-08-27 10:11 UTC, merged