404751 fix issues post method
DEFRA/epr-frontend-accountmanagement-microservice pull request #74
Opened 2024-08-01 14:49 UTC by MasilEviden

2024-08-01 15:04 UTC, tim-powell-eviden requested changes

2024-08-01 15:04 UTC, tim-powell-eviden commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +    private static bool SetUpdatableValue(bool isUpdatable, string serviceRole, string roleInOrganisation, EditUserDetailsViewModel model)
This method isn't fully covered by unit tests.

2024-08-01 15:04 UTC, tim-powell-eviden commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +        if (serviceRole.ToLower() == ServiceRoles.BasicUser.ToLower()
This condition is only partially unit tested.

2024-08-02 08:58 UTC, EvidenPete approved these changes

2024-08-02 10:54 UTC, tim-powell-eviden requested changes

2024-08-02 10:54 UTC, tim-powell-eviden commented on src/FrontendAccountManagement.Web/Controllers/AccountManagement/AccountManagementController.cs
> +                await _facadeService.UpdateUserDetails(userData.Id, userDetailsDto);
Needs unit testing.

2024-08-05 08:38 UTC, tim-powell-eviden approved these changes

2024-08-05 08:49 UTC, EvidenPete approved these changes

2024-08-05 08:58 UTC, merged